default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: 'tl17'
  password: 'password'
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: my_viblo_api_development

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: d689qvfr244igg
  username: ffmvonqimtcuqq
  password: b9fc02ec0f99f66c5c2fcc440415a69b9c41442f6f3f4c95c806f261755ad9e4
